sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
  - ".gradle"
  - "$HOME/.gradle"
  - "$HOME/.m2"
services: mysql
branches:
  only: master
env: DATABASE_URL="jdbc:mysql://localhost:3306/test" DATABASE_USERNAME="root"
before_install: "mysql -e 'create database test;'"
